Config = {}

Config.XpPerMinute = 4
Config.MaxXpPerLevel = 1000

Config.LevelPrice = 300		--Coins
Config.ResetPrice = 1000	--Coins

------MINIMUM VALUE MUST BE >= 60-----
Config.UpdateInterval = 600	--Seconds
--------------------------------------

--name is the inventory item and the image name
Config.Lootboxes = {
	[1] = {title = 'VEST LOOTBOX',				name = 'lb_vest',		type = 'item',		moneyPrice = nil,		coinPrice = 2500,	rarity = "LEGENDARY"},
	[2] = {title = 'MONEY LOOTBOX',				name = 'lb_money',		type = 'money',		moneyPrice = nil,		coinPrice = 2500,	rarity = "LEGENDARY"},
	[3] = {title = 'WEAPON LOOTBOX',			name = 'lb_weapon',		type = 'item',		moneyPrice = nil,		coinPrice = 2500,	rarity = "LEGENDARY"},
	[4] = {title = 'MEDKIT LOOTBOX',			name = 'lb_medkit',		type = 'item',		moneyPrice = nil,		coinPrice = 2500,	rarity = "LEGENDARY"},
	[5] = {title = 'VEHICLE LOOTBOX',			name = 'lb_vehicle',	type = 'vehicle',	moneyPrice = nil,		coinPrice = 2500,	rarity = "LEGENDARY"},
	[6] = {title = 'AIO LOOTBOX',				name = 'lb_aio',		type = 'random',	moneyPrice = 1000000,	coinPrice = 2500,	rarity = "LEGENDARY"},
	[7] = {title = 'PREMIUM VEHICLE LOOTBOX',	name = 'lb_pr_vehicle',	type = 'vehicle',	moneyPrice = nil,		coinPrice = 6000,	rarity = "LEGENDARY"},
	[8] = {title = 'BOOSTER POTION LOOTBOX',	name = 'lb_booster',	type = 'item',		moneyPrice = nil,		coinPrice = 2500,	rarity = "LEGENDARY"},
}

Config.LootboxesRewards = {
	[1] = {
		{name = 'bulletproof6',			label = 'Legendary Vest',		amount = 5,			luck = 2,  type = "EPIC"},
		{name = 'bulletproof5',			label = 'Mithril Vest',			amount = 5,			luck = 6,  type = "EPIC"},
		{name = 'bulletproof4',			label = 'Military Vest',		amount = 5,			luck = 25, type = "EPIC"},
		{name = 'bulletproof3',			label = 'Heavy Vest',			amount = 5,			luck = 20, type = "EPIC"},
		{name = 'bulletproof2',			label = 'Medium Vest',			amount = 5,			luck = 20, type = "EPIC"},
		{name = 'bulletproof1',			label = 'Light Vest',			amount = 5,			luck = 25, type = "EPIC"},
	},
	[2] = {
		{name = 'money',				label = '300000 Cash',			amount = 300000,	luck = 15, type = "EPIC"},
		{name = 'money',				label = '250000 Cash',			amount = 250000,	luck = 20, type = "EPIC"},
		{name = 'money',				label = '750000 Cash',			amount = 750000,	luck = 10, type = "EPIC"},
		{name = 'money',				label = '1000000 Cash',			amount = 1000000,	luck = 3,  type = "EPIC"},
		{name = 'money',				label = '500000 Cash',			amount = 500000,	luck = 15, type = "EPIC"},
		{name = 'money',				label = '2000000 Cash',			amount = 2000000,	luck = 1,  type = "EPIC"},
		{name = 'money',				label = '200000 Cash',			amount = 200000,	luck = 30, type = "EPIC"},
		{name = 'money',				label = '1500000 Cash',			amount = 1500000,	luck = 5,  type = "EPIC"},
	},
	[3] = {
		{name = 'blueprint_ISY',		label = 'Blueprint ISY',		amount = 1,			luck = 10, type = "EPIC"},
		{name = 'blueprint_SCARMK17',	label = 'Blueprint SCARMK17',	amount = 1,			luck = 10, type = "EPIC"},
		{name = 'blueprint_FOOL',		label = 'Blueprint FOOL',		amount = 1,			luck = 10, type = "EPIC"},
		{name = 'blueprint_GRAU',		label = 'Blueprint GRAU',		amount = 1,			luck = 10, type = "EPIC"},
		{name = 'blueprint_FNFAL',		label = 'Blueprint FNFAL',		amount = 1,			luck = 10, type = "EPIC"},
		{name = 'blueprint_M47',		label = 'Blueprint M47',		amount = 1,			luck = 10, type = "EPIC"},
		{name = 'blueprint_M82',		label = 'Blueprint M82',		amount = 1,			luck = 2,  type = "EPIC"},
		{name = 'blueprint_M133_2',		label = 'Blueprint M133 V2',		amount = 1,			luck = 10, type = "EPIC"},
		{name = 'blueprint_M4RIFLE',	label = 'Blueprint M4RIFLE',	amount = 1,			luck = 10, type = "EPIC"},
		{name = 'blueprint_CFS',		label = 'Blueprint CFS',		amount = 1,			luck = 2,  type = "EPIC"},
		{name = 'blueprint_SVD',		label = 'Blueprint SVD',		amount = 1,			luck = 3,  type = "EPIC"},
		{name = 'blueprint_M416P',		label = 'Blueprint M416P',		amount = 1,			luck = 5,  type = "EPIC"},
		{name = 'blueprint_NANITE',		label = 'Blueprint NANITE',		amount = 1,			luck = 5,  type = "EPIC"},
		{name = 'blueprint_PHANTOM',	label = 'Blueprint PHANTOM',	amount = 1,			luck = 1,  type = "EPIC"},
		{name = 'blueprint_M82',		label = 'Blueprint M82',		amount = 1,			luck = 1,  type = "EPIC"},
		{name = 'blueprint_SB181',		label = 'Blueprint SB181',		amount = 1,			luck = 1,  type = "EPIC"},
	},
	[4] = {
		{name = 'trifyllo_tsigaraki',	label =  'trifyllo tsigaraki',  amount = 10,        luck = 2,  type = "LEGENDARY"},
		{name = 'mytia_cocainis',		label =  'mytia cocainis',      amount = 10,        luck = 3,  type = "LEGENDARY"},
		{name = 'magic_potion',			label =  'magic potion',        amount = 20,        luck = 15, type = "LEGENDARY"},
		{name = 'super_potion',			label =  'super potion',        amount = 10,        luck = 5,  type = "LEGENDARY"},
		{name = 'painkiller3',			label =  'painkiller3',         amount = 10,        luck = 5,  type = "LEGENDARY"},
		{name = 'painkiller',			label =  'painkiller',          amount = 20,        luck = 15, type = "LEGENDARY"},
		{name = 'andrenaline',			label =  'andrenaline',         amount = 15,        luck = 10, type = "LEGENDARY"},
		{name = 'first_aid_kit',		label =  'first aid kit',       amount = 25,        luck = 15, type = "LEGENDARY"},
		{name = 'weapon_powerup',		label =  'weapon powerup',      amount = 35,        luck = 20, type = "LEGENDARY"},
		{name = 'cbd_water',			label =  'cbd water',           amount = 20,        luck = 15, type = "LEGENDARY"},
		
	},
	[5] = {
		{name = 'pbus2', label = 'pbus2', amount = 1, item_type = 'vehicle', luck = 10, type = "LEGENDARY"},
		{name = 'winky', label = 'winky', amount = 1, item_type = 'vehicle', luck = 10, type = "LEGENDARY"},
		{name = 'zhaba', label = 'zhaba', amount = 1, item_type = 'vehicle', luck = 10, type = "LEGENDARY"},
		{name = 'rcbandito', label = 'rcbandito', amount = 1, item_type = 'vehicle', luck = 10, type = "LEGENDARY"},
		{name = 'prmodlp750', label = 'prmodlp750', amount = 1, item_type = 'vehicle', luck = 5, type = "LEGENDARY"},
		{name = 'pevoque', label = 'pevoque', amount = 1, item_type = 'vehicle', luck = 5, type = "LEGENDARY"},
		{name = 'pbugatti', label = 'pbugatti', amount = 1, item_type = 'vehicle', luck = 5, type = "LEGENDARY"},
		{name = 'ab300', label = 'ab300', amount = 1, item_type = 'vehicle', luck = 2, type = "LEGENDARY"},
		{name = '488beast', label = '488beast', amount = 1, item_type = 'vehicle', luck = 2, type = "LEGENDARY"},
		{name = 'Urus_Stretch_6', label = 'Urus_Stretch_6', amount = 1, item_type = 'vehicle', luck = 2, type = "LEGENDARY"},
		{name = 'rr24gt500e', label = 'rr24gt500e', amount = 1, item_type = 'vehicle', luck = 2, type = "LEGENDARY"},
		{name = 'r8CSD', label = 'r8CSD', amount = 1, item_type = 'vehicle', luck = 2, type = "LEGENDARY"},
		{name = 'nightblade', label = 'nightblade', amount = 1, item_type = 'vehicle', luck = 10, type = "LEGENDARY"},
	},
	[6] = {
		{name = 'bulletproof6',         label = 'bulletproof6',         amount = 10,        luck = 10, type = "LEGENDARY"},
		{name = 'blueprint_PHANTOM',	label = 'Blueprint PHANTOM',	amount = 1,         luck = 5,  type = "LEGENDARY"},
		{name = 'blueprint_M82',		label = 'Blueprint M82',		amount = 1,         luck = 5,  type = "LEGENDARY"},
		{name = 'money',                label = '1500000 Cash',         amount = 1500000,   luck = 5,  type = "LEGENDARY"},
		{name = 'money',                label = '1000000 Cash',         amount = 1000000,   luck = 5,  type = "LEGENDARY"},
		{name = 'super_potion',         label = 'super potion',         amount = 15,        luck = 10, type = "LEGENDARY"},
		{name = 'mytia_cocainis',       label = 'mytia cocainis',       amount = 20,        luck = 15, type = "LEGENDARY"},
		{name = 'trifyllo_tsigaraki',   label = 'trifyllo tsigaraki',   amount = 20,        luck = 15, type = "LEGENDARY"},
		{name = 'first_aid_kit',        label = 'first aid kit',        amount = 25,        luck = 25, type = "LEGENDARY"},
	},
	[7] = {
		{name = 'crf450dakar',label = 'crf450dakar',amount = 1,item_type = 'vehicle',luck = 20,type = 'LEGENDARY'},
		{name = 'fer488beast',label = 'fer488beast',amount = 1,item_type = 'vehicle',luck = 20,type = 'LEGENDARY'},
		{name = 'ff7hardy',label = 'ff7hardy',amount = 1,item_type = 'vehicle',luck = 10,type = 'LEGENDARY'},
		{name = 'svj63',label = 'svj63',amount = 1,item_type = 'vehicle',luck = 10,type = 'LEGENDARY'},
		{name = 'nnmax',label = 'nnmax',amount = 1,item_type = 'vehicle',luck = 10,type = 'LEGENDARY'},
		{name = 'hbike3',label = 'hbike3',amount = 1,item_type = 'vehicle',luck = 1,type = 'LEGENDARY'},
		{name = '206wrc',label = '206wrc',    amount = 1,item_type = 'vehicle',luck = 10,type = 'LEGENDARY'},
		{name = 'bentaygast',label = 'bentaygast',    amount = 1,item_type = 'vehicle',luck = 10,type = 'LEGENDARY'},
		{name = 'bugattichiron',label = 'bugattichiron',amount = 1,item_type = 'vehicle',luck = 2,type = 'LEGENDARY'},
		{name = 'a45',label = 'a45',amount = 1,item_type = 'vehicle',luck = 2,type = 'LEGENDARY'},
		{name = 'golfp',label = 'golfp',amount = 1,item_type = 'vehicle',luck = 2,type = 'LEGENDARY'},
		{name = 'mq1',label = 'mq1',amount = 1,item_type = 'vehicle',luck = 2,type = 'LEGENDARY'},
		{name = 'monowheel',label = 'monowheel',amount = 1,item_type = 'vehicle',luck = 2,type = 'LEGENDARY'},
		{name = 'evo10',label = 'evo10',amount = 1,item_type = 'vehicle',luck = 1,type = 'LEGENDARY'},
		{name = 'sccjkl',label = 'sccjkl',amount = 1,item_type = 'vehicle',luck = 1,type = 'LEGENDARY'},
		{name = '488speedter',label = '488speedter',amount = 1,item_type = 'vehicle',luck = 1,type = 'LEGENDARY'},
		{name = 'sphere',label = 'sphere',amount = 1,item_type = 'vehicle',luck = 1,type = 'LEGENDARY'},
		{name = 'sharkm4',label = 'sharkm4',amount = 1,item_type = 'vehicle',luck = 1,type = 'LEGENDARY'},
		{name = 'jltv',label = 'jltv',amount = 1,item_type = 'vehicle',luck = 2,type = 'LEGENDARY'},
		{name = 'm4gt3',label = 'm4gt3',amount = 1,item_type = 'vehicle',luck = 5,type = 'LEGENDARY'},
		{name = 'tmax560tech',label = 'tmax560tech',amount = 1,item_type = 'vehicle',luck = 10,type = 'LEGENDARY'},
		{name = 'KR200',label = 'KR200',amount = 1,item_type = 'vehicle',luck = 10,type = 'LEGENDARY'},
		{name = 'evija',label = 'evija',amount = 1,item_type = 'vehicle',luck = 5,type = 'LEGENDARY'},
		{name = 'rmodm4n',label = 'rmodm4n',amount = 1,item_type = 'vehicle',luck = 5,type = 'LEGENDARY'},
		{name = 'SonicMustang',label = 'SonicMustang',amount = 1,item_type = 'vehicle',luck = 5,type = 'LEGENDARY'},
		{name = 'artura22wb',label = 'artura22wb',amount = 1,item_type = 'vehicle',luck = 5,type = 'LEGENDARY'},
	},
	[8] = {
		{name = 'super_potion2',		label = 'Booster Potion',		amount = 1,			luck = 10,	type = "LEGENDARY"},
		{name = 'super_potion',			label = 'Super Potion',			amount = 1,			luck = 35,	type = "LEGENDARY"},
		{name = 'magic_potion',			label = 'Potion',				amount = 1,			luck = 55,	type = "LEGENDARY"},
	},
}

Config.LevelRewards = {
	{title = 'MONEY',					item = 'cash',					amount = 150000,	type = 'money',			desc = 'WIN 50000 CASH'},

	{title = 'ISY',						item = 'blueprint_ISY',			amount = 3,			type = 'item',			desc = 'WIN x3 ISY AUTOMATIC RIFLE'},
	{title = 'COINS',					item = 'coin',					amount = 100,		type = 'coin',			desc = 'WIN 100 DONATE COINS'},
	{title = 'MILITARY VESTS',			item = 'bulletproof4',			amount = 5,			type = 'item',			desc = 'WIN 5 MILITARY VESTS'},
	{title = 'RIFLE AMMO',				item = 'AMMO_RIFLE',			amount = 5,			type = 'item',			desc = 'WIN 5 RIFLE AMMO'},
	{title = 'TRIFYLLO TSIGARAKI',		item = 'trifyllo_tsigaraki',	amount = 5,			type = 'item',			desc = 'WIN 5 TRIFYLLO TSIGARAKI </br>(10% REDUCED DAMAGE)'},
	{title = 'MYTIA COCAINIS',			item = 'mytia_cocainis',		amount = 5,			type = 'item',			desc = 'WIN 5 MYTIA COCAINIS </br>(10% INCREASE DAMAGE)'},
	{title = 'WEAPON SCROLLS',			item = 'weapon_powerup',		amount = 10,		type = 'item',			desc = 'WIN 10 WEAPON SCROLLS </br>(10% INCREASE DAMAGE)'},
	{title = 'EXPERIENCE CARDS',		item = 'experience_card',		amount = 5,			type = 'item',			desc = 'WIN 5 EXPERIENCE CARDS </br>(INCREASE MAFIA XP)'},
	{title = 'BLACK MONEY',				item = 'black_money',			amount = 50000,		type = 'black_money',	desc = 'WIN 20000 BLACK MONEY'},
	{title = 'MONEY',					item = 'cash',					amount = 150000,	type = 'money',			desc = 'WIN 50000 CASH'},

	{title = 'M133 V2',					item = 'blueprint_M133_2',		amount = 3,			type = 'item',			desc = 'WIN x3 M133 V2 AUTOMATIC RIFLE'},
	{title = 'COINS',					item = 'coin',					amount = 100,		type = 'coin',			desc = 'WIN 100 DONATE COINS'},
	{title = 'MILITARY VESTS',			item = 'bulletproof4',			amount = 5,			type = 'item',			desc = 'WIN 5 MILITARY VESTS'},
	{title = 'RIFLE AMMO',				item = 'AMMO_RIFLE',			amount = 5,			type = 'item',			desc = 'WIN 5 RIFLE AMMO'},
	{title = 'TRIFYLLO TSIGARAKI',		item = 'trifyllo_tsigaraki',	amount = 5,			type = 'item',			desc = 'WIN 5 TRIFYLLO TSIGARAKI </br>(10% REDUCED DAMAGE)'},
	{title = 'MYTIA COCAINIS',			item = 'mytia_cocainis',		amount = 5,			type = 'item',			desc = 'WIN 5 MYTIA COCAINIS </br>(10% INCREASE DAMAGE)'},
	{title = 'WEAPON SCROLLS',			item = 'weapon_powerup',		amount = 10,		type = 'item',			desc = 'WIN 10 WEAPON SCROLLS </br>(10% INCREASE DAMAGE)'},
	{title = 'EXPERIENCE CARDS',		item = 'experience_card',		amount = 5,			type = 'item',			desc = 'WIN 5 EXPERIENCE CARDS </br>(INCREASE MAFIA XP)'},
	{title = 'BLACK MONEY',				item = 'black_money',			amount = 50000,		type = 'black_money',	desc = 'WIN 20000 BLACK MONEY'},
	{title = 'MONEY',					item = 'cash',					amount = 150000,	type = 'money',			desc = 'WIN 50000 CASH'},

	{title = 'FOOL',					item = 'blueprint_FOOL',		amount = 3,			type = 'item',			desc = 'WIN x3 FOOL AUTOMATIC RIFLE'},
	{title = 'COINS',					item = 'coin',					amount = 100,		type = 'coin',			desc = 'WIN 100 DONATE COINS'},
	{title = 'MILITARY VESTS',			item = 'bulletproof4',			amount = 5,			type = 'item',			desc = 'WIN 5 MILITARY VESTS'},
	{title = 'RIFLE AMMO',				item = 'AMMO_RIFLE',			amount = 5,			type = 'item',			desc = 'WIN 5 RIFLE AMMO'},
	{title = 'TRIFYLLO TSIGARAKI',		item = 'trifyllo_tsigaraki',	amount = 5,			type = 'item',			desc = 'WIN 5 TRIFYLLO TSIGARAKI </br>(10% REDUCED DAMAGE)'},
	{title = 'MYTIA COCAINIS',			item = 'mytia_cocainis',		amount = 5,			type = 'item',			desc = 'WIN 5 MYTIA COCAINIS </br>(10% INCREASE DAMAGE)'},
	{title = 'WEAPON SCROLLS',			item = 'weapon_powerup',		amount = 10,		type = 'item',			desc = 'WIN 10 WEAPON SCROLLS </br>(10% INCREASE DAMAGE)'},
	{title = 'EXPERIENCE CARDS',		item = 'experience_card',		amount = 5,			type = 'item',			desc = 'WIN 5 EXPERIENCE CARDS </br>(INCREASE MAFIA XP)'},
	{title = 'BLACK MONEY',				item = 'black_money',			amount = 50000,		type = 'black_money',	desc = 'WIN 20000 BLACK MONEY'},
	{title = 'MONEY',					item = 'cash',					amount = 150000,	type = 'money',			desc = 'WIN 50000 CASH'},

	{title = 'ICEDRAKE',				item = 'blueprint_ICEDRAKE',	amount = 3,			type = 'item',			desc = 'WIN x3 ICEDRAKE AUTOMATIC RIFLE'},
	{title = 'COINS',					item = 'coin',					amount = 100,		type = 'coin',			desc = 'WIN 100 DONATE COINS'},
	{title = 'MILITARY VESTS',			item = 'bulletproof4',			amount = 5,			type = 'item',			desc = 'WIN 5 MILITARY VESTS'},
	{title = 'RIFLE AMMO',				item = 'AMMO_RIFLE',			amount = 5,			type = 'item',			desc = 'WIN 5 RIFLE AMMO'},
	{title = 'TRIFYLLO TSIGARAKI',		item = 'trifyllo_tsigaraki',	amount = 5,			type = 'item',			desc = 'WIN 5 TRIFYLLO TSIGARAKI </br>(10% REDUCED DAMAGE)'},
	{title = 'MYTIA COCAINIS',			item = 'mytia_cocainis',		amount = 5,			type = 'item',			desc = 'WIN 5 MYTIA COCAINIS </br>(10% INCREASE DAMAGE)'},
	{title = 'WEAPON SCROLLS',			item = 'weapon_powerup',		amount = 10,		type = 'item',			desc = 'WIN 10 WEAPON SCROLLS </br>(10% INCREASE DAMAGE)'},
	{title = 'EXPERIENCE CARDS',		item = 'experience_card',		amount = 5,			type = 'item',			desc = 'WIN 5 EXPERIENCE CARDS </br>(INCREASE MAFIA XP)'},
	{title = 'BLACK MONEY',				item = 'black_money',			amount = 50000,		type = 'black_money',	desc = 'WIN 20000 BLACK MONEY'},
	{title = 'MONEY',					item = 'cash',					amount = 150000,	type = 'money',			desc = 'WIN 50000 CASH'},

	{title = 'MOON',					item = 'blueprint_MOON',		amount = 3,			type = 'item',			desc = 'WIN x3 MOON AUTOMATIC RIFLE'},
	{title = 'COINS',					item = 'coin',					amount = 100,		type = 'coin',			desc = 'WIN 100 DONATE COINS'},
	{title = 'MILITARY VESTS',			item = 'bulletproof4',			amount = 5,			type = 'item',			desc = 'WIN 5 MILITARY VESTS'},
	{title = 'RIFLE AMMO',				item = 'AMMO_RIFLE',			amount = 5,			type = 'item',			desc = 'WIN 5 RIFLE AMMO'},
	{title = 'TRIFYLLO TSIGARAKI',		item = 'trifyllo_tsigaraki',	amount = 5,			type = 'item',			desc = 'WIN 5 TRIFYLLO TSIGARAKI </br>(10% REDUCED DAMAGE)'},
	{title = 'MYTIA COCAINIS',			item = 'mytia_cocainis',		amount = 5,			type = 'item',			desc = 'WIN 5 MYTIA COCAINIS </br>(10% INCREASE DAMAGE)'},
	{title = 'WEAPON SCROLLS',			item = 'weapon_powerup',		amount = 10,		type = 'item',			desc = 'WIN 10 WEAPON SCROLLS </br>(10% INCREASE DAMAGE)'},
	{title = 'EXPERIENCE CARDS',		item = 'experience_card',		amount = 5,			type = 'item',			desc = 'WIN 5 EXPERIENCE CARDS </br>(INCREASE MAFIA XP)'},
	{title = 'BLACK MONEY',				item = 'black_money',			amount = 50000,		type = 'black_money',	desc = 'WIN 20000 BLACK MONEY'},
	{title = 'MONEY',					item = 'cash',					amount = 150000,	type = 'money',			desc = 'WIN 50000 CASH'},

	{title = 'CAUSTIC',					item = 'blueprint_CAUSTIC',		amount = 3,			type = 'item',			desc = 'WIN x3 CAUSTIC AUTOMATIC RIFLE'},
	{title = 'COINS',					item = 'coin',					amount = 100,		type = 'coin',			desc = 'WIN 100 DONATE COINS'},
	{title = 'MILITARY VESTS',			item = 'bulletproof4',			amount = 5,			type = 'item',			desc = 'WIN 5 MILITARY VESTS'},
	{title = 'RIFLE AMMO',				item = 'AMMO_RIFLE',			amount = 5,			type = 'item',			desc = 'WIN 5 RIFLE AMMO'},
	{title = 'TRIFYLLO TSIGARAKI',		item = 'trifyllo_tsigaraki',	amount = 5,			type = 'item',			desc = 'WIN 5 TRIFYLLO TSIGARAKI </br>(10% REDUCED DAMAGE)'},
	{title = 'MYTIA COCAINIS',			item = 'mytia_cocainis',		amount = 5,			type = 'item',			desc = 'WIN 5 MYTIA COCAINIS </br>(10% INCREASE DAMAGE)'},
	{title = 'WEAPON SCROLLS',			item = 'weapon_powerup',		amount = 10,		type = 'item',			desc = 'WIN 10 WEAPON SCROLLS </br>(10% INCREASE DAMAGE)'},
	{title = 'EXPERIENCE CARDS',		item = 'experience_card',		amount = 5,			type = 'item',			desc = 'WIN 5 EXPERIENCE CARDS </br>(INCREASE MAFIA XP)'},
	{title = 'BLACK MONEY',				item = 'black_money',			amount = 50000,		type = 'black_money',	desc = 'WIN 20000 BLACK MONEY'},
	{title = 'MONEY',					item = 'cash',					amount = 150000,	type = 'money',			desc = 'WIN 50000 CASH'},

	{title = 'FNFAL',					item = 'blueprint_FNFAL',		amount = 3,			type = 'item',			desc = 'WIN x3 FNFAL AUTOMATIC RIFLE'},
	{title = 'COINS',					item = 'coin',					amount = 100,		type = 'coin',			desc = 'WIN 100 DONATE COINS'},
	{title = 'MILITARY VESTS',			item = 'bulletproof4',			amount = 5,			type = 'item',			desc = 'WIN 5 MILITARY VESTS'},
	{title = 'RIFLE AMMO',				item = 'AMMO_RIFLE',			amount = 5,			type = 'item',			desc = 'WIN 5 RIFLE AMMO'},
	{title = 'TRIFYLLO TSIGARAKI',		item = 'trifyllo_tsigaraki',	amount = 5,			type = 'item',			desc = 'WIN 5 TRIFYLLO TSIGARAKI </br>(10% REDUCED DAMAGE)'},
	{title = 'MYTIA COCAINIS',			item = 'mytia_cocainis',		amount = 5,			type = 'item',			desc = 'WIN 5 MYTIA COCAINIS </br>(10% INCREASE DAMAGE)'},
	{title = 'WEAPON SCROLLS',			item = 'weapon_powerup',		amount = 10,		type = 'item',			desc = 'WIN 10 WEAPON SCROLLS </br>(10% INCREASE DAMAGE)'},
	{title = 'EXPERIENCE CARDS',		item = 'experience_card',		amount = 5,			type = 'item',			desc = 'WIN 5 EXPERIENCE CARDS </br>(INCREASE MAFIA XP)'},
	{title = 'BLACK MONEY',				item = 'black_money',			amount = 50000,		type = 'black_money',	desc = 'WIN 20000 BLACK MONEY'},
	{title = 'MONEY',					item = 'cash',					amount = 150000,	type = 'money',			desc = 'WIN 50000 CASH'},

	{title = 'NV4',						item = 'blueprint_NV4',			amount = 3,			type = 'item',			desc = 'WIN x3 NV4 AUTOMATIC RIFLE'},
	{title = 'COINS',					item = 'coin',					amount = 100,		type = 'coin',			desc = 'WIN 100 DONATE COINS'},
	{title = 'MILITARY VESTS',			item = 'bulletproof4',			amount = 5,			type = 'item',			desc = 'WIN 5 MILITARY VESTS'},
	{title = 'RIFLE AMMO',				item = 'AMMO_RIFLE',			amount = 5,			type = 'item',			desc = 'WIN 5 RIFLE AMMO'},
	{title = 'TRIFYLLO TSIGARAKI',		item = 'trifyllo_tsigaraki',	amount = 5,			type = 'item',			desc = 'WIN 5 TRIFYLLO TSIGARAKI </br>(10% REDUCED DAMAGE)'},
	{title = 'MYTIA COCAINIS',			item = 'mytia_cocainis',		amount = 5,			type = 'item',			desc = 'WIN 5 MYTIA COCAINIS </br>(10% INCREASE DAMAGE)'},
	{title = 'WEAPON SCROLLS',			item = 'weapon_powerup',		amount = 10,		type = 'item',			desc = 'WIN 10 WEAPON SCROLLS </br>(10% INCREASE DAMAGE)'},
	{title = 'EXPERIENCE CARDS',		item = 'experience_card',		amount = 5,			type = 'item',			desc = 'WIN 5 EXPERIENCE CARDS </br>(INCREASE MAFIA XP)'},
	{title = 'BLACK MONEY',				item = 'black_money',			amount = 50000,		type = 'black_money',	desc = 'WIN 20000 BLACK MONEY'},
	{title = 'MONEY',					item = 'cash',					amount = 150000,	type = 'money',			desc = 'WIN 50000 CASH'},

	{title = 'ARC15',					item = 'blueprint_ARC15',		amount = 3,			type = 'item',			desc = 'WIN x3 ARC15 AUTOMATIC RIFLE'},
	{title = 'COINS',					item = 'coin',					amount = 100,		type = 'coin',			desc = 'WIN 100 DONATE COINS'},
	{title = 'MILITARY VESTS',			item = 'bulletproof4',			amount = 5,			type = 'item',			desc = 'WIN 5 MILITARY VESTS'},
	{title = 'RIFLE AMMO',				item = 'AMMO_RIFLE',			amount = 5,			type = 'item',			desc = 'WIN 5 RIFLE AMMO'},
	{title = 'TRIFYLLO TSIGARAKI',		item = 'trifyllo_tsigaraki',	amount = 5,			type = 'item',			desc = 'WIN 5 TRIFYLLO TSIGARAKI </br>(10% REDUCED DAMAGE)'},
	{title = 'MYTIA COCAINIS',			item = 'mytia_cocainis',		amount = 5,			type = 'item',			desc = 'WIN 5 MYTIA COCAINIS </br>(10% INCREASE DAMAGE)'},
	{title = 'WEAPON SCROLLS',			item = 'weapon_powerup',		amount = 10,		type = 'item',			desc = 'WIN 10 WEAPON SCROLLS </br>(10% INCREASE DAMAGE)'},
	{title = 'EXPERIENCE CARDS',		item = 'experience_card',		amount = 5,			type = 'item',			desc = 'WIN 5 EXPERIENCE CARDS </br>(INCREASE MAFIA XP)'},
	{title = 'BLACK MONEY',				item = 'black_money',			amount = 50000,		type = 'black_money',	desc = 'WIN 20000 BLACK MONEY'},
	{title = 'MONEY',					item = 'cash',					amount = 150000,	type = 'money',			desc = 'WIN 50000 CASH'},

	{title = 'PAINFUL',						item = 'blueprint_PAINFUL',			amount = 3,			type = 'item',			desc = 'WIN x3 PAINFUL AUTOMATIC RIFLE'},
	{title = 'COINS',					item = 'coin',					amount = 100,		type = 'coin',			desc = 'WIN 100 DONATE COINS'},
	{title = 'MILITARY VESTS',			item = 'bulletproof4',			amount = 5,			type = 'item',			desc = 'WIN 5 MILITARY VESTS'},
	{title = 'RIFLE AMMO',				item = 'AMMO_RIFLE',			amount = 5,			type = 'item',			desc = 'WIN 5 RIFLE AMMO'},
	{title = 'TRIFYLLO TSIGARAKI',		item = 'trifyllo_tsigaraki',	amount = 5,			type = 'item',			desc = 'WIN 5 TRIFYLLO TSIGARAKI </br>(10% REDUCED DAMAGE)'},
	{title = 'MYTIA COCAINIS',			item = 'mytia_cocainis',		amount = 5,			type = 'item',			desc = 'WIN 5 MYTIA COCAINIS </br>(10% INCREASE DAMAGE)'},
	{title = 'WEAPON SCROLLS',			item = 'weapon_powerup',		amount = 10,		type = 'item',			desc = 'WIN 10 WEAPON SCROLLS </br>(10% INCREASE DAMAGE)'},
	{title = 'EXPERIENCE CARDS',		item = 'experience_card',		amount = 5,			type = 'item',			desc = 'WIN 5 EXPERIENCE CARDS </br>(INCREASE MAFIA XP)'},
	{title = 'BLACK MONEY',				item = 'black_money',			amount = 50000,		type = 'black_money',	desc = 'WIN 20000 BLACK MONEY'},
	{title = 'MONEY',					item = 'cash',					amount = 150000,	type = 'money',			desc = 'WIN 50000 CASH'},
}