Config = {}

Config.PercentToSociety = 10

Config.Gunshops = {
	['customgunshop1'] = {
		coords = vector3(-44.81, -198.74, 45.79),
		heading = 150.00,
		model = `s_m_y_ammucity_01`,
		menu = 'default',
	},
}

Config.WeaponMenus = {
	['default'] = {
		['rifle'] = {
			{
				name = 'WEAPON_M9_P_CHROMIUM',
				price = 400000,
				account = 'money',
				weight = 1.0,
				stats = {damage = 10, recoil = 20, range = 30},
				itemsNeeded = {},
			},
			{
				name = 'WEAPON_CAUSTIC',
				price = 400000,
				account = 'money',
				weight = 1.0,
				stats = {damage = 10, recoil = 20, range = 30},
				itemsNeeded = {},
			},
			{
				name = 'WEAPON_L96A3',
				price = 400000,
				account = 'money',
				weight = 1.0,
				stats = {damage = 10, recoil = 20, range = 30},
				itemsNeeded = {},
			},
			{
				name = 'WEAPON_HFAP',
				price = 400000,
				account = 'money',
				weight = 1.0,
				stats = {damage = 10, recoil = 20, range = 30},
				itemsNeeded = {},
			},
			{
				name = 'WEAPON_LIMITLESS_CARBINE_MK2',
				price = 400000,
				account = 'money',
				weight = 1.0,
				stats = {damage = 10, recoil = 20, range = 30},
				itemsNeeded = {},
			},
			{
				name = 'WEAPON_SALTY_SNACK',
				price = 400000,
				account = 'money',
				weight = 1.0,
				stats = {damage = 10, recoil = 20, range = 30},
				itemsNeeded = {},
			},
			{
				name = 'WEAPON_L85_CHRISTMAS',
				price = 400000,
				account = 'money',
				weight = 1.0,
				stats = {damage = 10, recoil = 20, range = 30},
				itemsNeeded = {},
			},
			{
				name = 'WEAPON_MP5X',
				price = 400000,
				account = 'money',
				weight = 1.0,
				stats = {damage = 10, recoil = 20, range = 30},
				itemsNeeded = {},
			},
			{
				name = 'WEAPON_PAINFUL',
				price = 400000,
				account = 'money',
				weight = 1.0,
				stats = {damage = 10, recoil = 20, range = 30},
				itemsNeeded = {},
			},
			{
				name = 'WEAPON_HFSMG',
				price = 400000,
				account = 'money',
				weight = 1.0,
				stats = {damage = 10, recoil = 20, range = 30},
				itemsNeeded = {},
			},
			{
				name = 'WEAPON_AK47_NIGHTWISH',
				price = 400000,
				account = 'money',
				weight = 1.0,
				stats = {damage = 10, recoil = 20, range = 30},
				itemsNeeded = {},
			},
			{
				name = 'WEAPON_M4A1_CHROMIUM',
				price = 400000,
				account = 'money',
				weight = 1.0,
				stats = {damage = 10, recoil = 20, range = 30},
				itemsNeeded = {},
			},
			{
				name = 'WEAPON_CROCDILE',
				price = 400000,
				account = 'money',
				weight = 1.0,
				stats = {damage = 10, recoil = 20, range = 30},
				itemsNeeded = {},
			},
			{
				name = 'WEAPON_TIGER',
				price = 400000,
				account = 'money',
				weight = 1.0,
				stats = {damage = 10, recoil = 20, range = 30},
				itemsNeeded = {},
			},
			{
				name = 'WEAPON_REDDRAGON',
				price = 400000,
				account = 'money',
				weight = 1.0,
				stats = {damage = 10, recoil = 20, range = 30},
				itemsNeeded = {},
			},
			{
				name = 'WEAPON_VERESK',
				price = 400000,
				account = 'money',
				weight = 1.0,
				stats = {damage = 10, recoil = 20, range = 30},
				itemsNeeded = {},
			},
			{
				name = 'WEAPON_ISYV2',
				price = 400000,
				account = 'money',
				weight = 1.0,
				stats = {damage = 10, recoil = 20, range = 30},
				itemsNeeded = {},
			},
			{
				name = 'WEAPON_MSG4A1SR',
				price = 400000,
				account = 'money',
				weight = 1.0,
				stats = {damage = 10, recoil = 20, range = 30},
				itemsNeeded = {},
			},
			{
				name = 'WEAPON_HFSMGV2',
				price = 400000,
				account = 'money',
				weight = 1.0,
				stats = {damage = 10, recoil = 20, range = 30},
				itemsNeeded = {},
			},
			{
				name = 'WEAPON_HEAVYSNIPER',
				price = 400000,
				account = 'money',
				weight = 1.0,
				stats = {damage = 10, recoil = 20, range = 30},
				itemsNeeded = {},
			},			
		},
	},
}